# Generated by Django 5.0.3 on 2024-03-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_user_contact_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_joining',
        ),
    ]
