# Generated by Django 5.0.3 on 2024-03-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_user_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(max_length=10, verbose_name='blood_group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_address',
            field=models.CharField(max_length=100, verbose_name='contact_address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='phone_number'),
        ),
    ]
