# Generated by Django 5.0.3 on 2024-03-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='role',
        ),
        migrations.AddField(
            model_name='designation',
            name='designation',
            field=models.CharField(default='developer', max_length=20, unique=True, verbose_name='designation'),
        ),
    ]
