# Generated by Django 5.0.3 on 2024-03-10 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_designation_role_designation_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.designation', verbose_name='designation'),
        ),
    ]
